//
// CharacterList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CharacterList: Codable {

    /** The number of total available characters in this list. Will always be greater than or equal to the \"returned\" value. */
    public var available: Int?
    /** The number of characters returned in this collection (up to 20). */
    public var returned: Int?
    /** The path to the full list of characters in this collection. */
    public var collectionURI: String?
    /** The list of returned characters in this collection. */
    public var items: [CharacterSummary]?

    public init(available: Int? = nil, returned: Int? = nil, collectionURI: String? = nil, items: [CharacterSummary]? = nil) {
        self.available = available
        self.returned = returned
        self.collectionURI = collectionURI
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case available
        case returned
        case collectionURI
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(available, forKey: .available)
        try container.encodeIfPresent(returned, forKey: .returned)
        try container.encodeIfPresent(collectionURI, forKey: .collectionURI)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

