//
// CharacterSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CharacterSummary: Codable {

    /** The path to the individual character resource. */
    public var resourceURI: String?
    /** The full name of the character. */
    public var name: String?
    /** The role of the creator in the parent entity. */
    public var role: String?

    public init(resourceURI: String? = nil, name: String? = nil, role: String? = nil) {
        self.resourceURI = resourceURI
        self.name = name
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resourceURI
        case name
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(resourceURI, forKey: .resourceURI)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

