//
// ComicPrice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ComicPrice: Codable, Hashable {

    /** A description of the price (e.g. print price, digital price). */
    public var type: String?
    /** The price (all prices in USD). */
    public var price: Float?

    public init(type: String? = nil, price: Float? = nil) {
        self.type = type
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(price, forKey: .price)
    }
}

