//
// EventSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EventSummary: Codable, Hashable {

    /** The path to the individual event resource. */
    public var resourceURI: String?
    /** The name of the event. */
    public var name: String?

    public init(resourceURI: String? = nil, name: String? = nil) {
        self.resourceURI = resourceURI
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resourceURI
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(resourceURI, forKey: .resourceURI)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

