//
// Image.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Image: Codable {

    /** The directory path of to the image. */
    public var path: String?
    /** The file extension for the image. */
    public var _extension: String?

    public init(path: String? = nil, _extension: String? = nil) {
        self.path = path
        self._extension = _extension
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case _extension = "extension"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(_extension, forKey: ._extension)
    }
}

